#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
name: Pinot Docker Image Build and Publish on Self hosted EC2 instances

on:
  workflow_dispatch:
    inputs:
      gitUrl:
        description: "The Pinot git repo to check out to build, use https."
        default: "https://github.com/apache/pinot.git"
        required: true
      commit:
        description: "The branch/commit to check out to build Pinot image."
        default: "master"
        required: true
      platform:
        description: "The platform of the image to build, e.g. linux/amd64,linux/arm64"
        default: "linux/amd64"
        required: true
      dockerImageName:
        description: "The docker image name, default to 'apachepinot/pinot'."
        default: "apachepinot/pinot"
        required: true
      tags:
        description: "Tags to push of the image, comma separated, e.g. tag1,tag2,tag3"
        default: ""
      kafkaVersion:
        description: "Kafka version"
        default: "2.0"
      jdkVersion:
        description: "JDK version"
        default: "11"

jobs:
  start-runner:
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.GH_TOKEN }}
          ec2-image-id: ami-098001493b2a003e1 
          ec2-instance-type: m6i.4xlarge
          subnet-id: subnet-0f942a967739708b7
          security-group-id: sg-0e48cb925e023f746
  do-the-job:
    name: Do the job on the runner
    needs: start-runner # required to start the main job when the runner is ready
    runs-on: ${{ needs.start-runner.outputs.label }} # run the job on the newly created runner
    steps:
      - name: Hello World
        run: echo 'Hello World!'
  build-pinot-docker-image:
    name: Build Pinot Docker Image
    needs: start-runner
    runs-on: ${{ needs.start-runner.outputs.label }}
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/setup-qemu-action@v1
      name: Set up QEMU
    - uses: docker/setup-buildx-action@v1
      name: Set up Docker Buildx
    - uses: actions/checkout@v3
    - name: Build and push the Docker image
      env:
        DOCKER_FILE_BASE_DIR: "docker/images/pinot"
        DOCKER_IMAGE_NAME: ${{ github.event.inputs.dockerImageName }}
        BUILD_PLATFORM: ${{ github.event.inputs.platform }}
        PINOT_GIT_URL: ${{ github.event.inputs.gitUrl }}
        PINOT_BRANCH: ${{ github.event.inputs.commit }}
        KAFKA_VERSION: ${{ github.event.inputs.kafkaVersion }}
        JDK_VERSION: ${{ github.event.inputs.jdkVersion }}
        TAGS: ${{ github.event.inputs.tags }}
      run: .github/workflows/scripts/docker/.pinot_docker_image_build_and_push.sh
  stop-runner:
    name: Stop self-hosted EC2 runner
    needs:
      - start-runner # required to get output from the start-runner job
      - build-pinot-docker-image # required to wait when the main job is done
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.GH_TOKEN }}
          label: ${{ needs.start-runner.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}